import turtle
print("Loading Turtle Graphics...")
print("Succesfully loaded!")
turtle.forward(375)
turtle.color("purple")
turtle.left(90)
turtle.forward(375)
turtle.color("green")
turtle.left(90)
turtle.forward(375)
turtle.color("red")
turtle.left(90)
turtle.forward(375)
print("Turtle Graphics commands loaded!")
input("Press Enter to exit...")
exit()
